//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.Client.Api.Wcf.WAS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kf.com/WASHost", ConfigurationName="Api.Wcf.WAS.WasHost")]
    public interface WasHost {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kf.com/WASHost/WasHost/HelloWCF", ReplyAction="http://www.kf.com/WASHost/WasHost/HelloWCFResponse")]
        string HelloWCF();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kf.com/WASHost/WasHost/HelloWCF", ReplyAction="http://www.kf.com/WASHost/WasHost/HelloWCFResponse")]
        System.Threading.Tasks.Task<string> HelloWCFAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WasHostChannel : WCF.Client.Api.Wcf.WAS.WasHost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WasHostClient : System.ServiceModel.ClientBase<WCF.Client.Api.Wcf.WAS.WasHost>, WCF.Client.Api.Wcf.WAS.WasHost {
        
        public WasHostClient() {
        }
        
        public WasHostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WasHostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WasHostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WasHostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWCF() {
            return base.Channel.HelloWCF();
        }
        
        public System.Threading.Tasks.Task<string> HelloWCFAsync() {
            return base.Channel.HelloWCFAsync();
        }
    }
}
