// ATLProject.idl : ATLProject 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(ATLProject.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,	
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(0E15C7DF-805F-4612-8699-48730EC9BD64),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IFirstClass : IDispatch{
	[id(1)] HRESULT Add([in] LONG para1, [in] LONG para2, [out, retval] LONG* result);
};
[
	uuid(E4256895-EA06-4555-ABE4-D0D1247D5880),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{356977EF-71AF-4FD3-8871-077791858A1E}")
]
library ATLProjectLib
{
	importlib("stdole2.tlb");
	[
		uuid(356977EF-71AF-4FD3-8871-077791858A1E)		
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
	[
		uuid(687802F5-A75C-44C6-A0F1-611C124FD90E)		
	]
	coclass FirstClass
	{
		[default] interface IFirstClass;
	};
};

